current_dashboard: 0
dashboards:
- cols: 3
  entities:
  - display_name: "Lumin\u0103"
    entity: light.light_switch1_light
    icon: null
    position:
    - 0
    - 0
    type: auto
  - display_name: Fan
    entity: switch.relay_1
    icon: null
    position:
    - 1
    - 1
    type: auto
  name: Default Dashboard
  refresh_interval: 5
  rows: 3
- cols: 3
  entities:
  - display_name: Stalinskaya
    entity: light.stalinskaya
    icon: null
    position:
    - 1
    - 1
    type: auto
  name: test2
  refresh_interval: 5
  rows: 3
