dashboard:
  name: "Main Dashboard"
  refresh_interval: 3
  rows: 3
  cols: 3
  entities:
    - entity: light.bedroom1_main_desk_alarm_light
      row: 0
      col: 0
      type: toggle
    - entity: light.light_switch1_light
      row: 0
      col: 1
      type: toggle
